### PR TITLE
Auto build & package

### PR DESCRIPTION
**Pull request by markhicken**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] I have updated the Experience League documentation for the [Core Extension](https://git.corp.adobe.com/AdobeDocs/experience-platform.en/tree/master/help/tags/extensions/web/core)
- [ ] All tests pass and I've made any necessary test changes.
- [ ] I have run the extension sandbox successfully.

### CODE REVIEW

**Comment by jbarchibald** [comment]
Looks like this did compile OK,  where would i look to find this dist/ folder?

**Comment by markhicken** [comment]
> Looks like this did compile OK, where would i look to find this dist/ folder?

I'm not sure. I think we need to read up on `https://github.com/actions/upload-artifact#zipped-artifact-downloads`
Also, I need to update it to only upload the packaged zip file rather than the whole `dist` folder.

**Comment by markhicken** [comment]
Ok, I have this fixed. It now only uploads the extension package. The key is that it needs to be versioned as part of the PR. 
The workflow log now echos a direct link to the artifact. 

@brenthosie are you aware of any CI constraints (build limits, storage limits, etc)? We might need to periodically cleanup old builds if they don't do it for us.

**Comment by markhicken** [comment]
Ok, apparently renaming the branch closes the PR. :( 

Moved to [new PR over here](https://github.com/adobe/reactor-extension-core/pull/87).

**Pull request closed without merging**
