### PR TITLE
Adding new Data Elements to reduce the need for Custom Code

### PR DESCRIPTION
**Pull request by frederikwerner**
## Description

This pull requests adds four new Data Elements:
- Conditional Value: Basically a wrapper for the "Value Comparison" condition (code is basically a 1:1 copy), but can return one of two values based on the result of the comparison. Can thereby handle "If... Then... Else..." scenarios without the need for extra rules.
- Launch Environment: Contains 8 pieces of information about the Launch environment:
  - Environment Stage: Returns _satellite.buildInfo.environment to differentiate between dev/staging/prod environments
  - Library Build Date: Returns _satellite.buildInfo.buildDate to monitor library versions
  - Property Name: Returns _satellite.property.name to get the name of the Launch property
  - Rule Name: Returns event.$rule.name containing the name of the executed rule
  - Rule Id: Returns event.$rule.id containing the Id of the executed rule
  - Event Type: Returns event.$type containing the type of event that triggered the rule
  - Event Detail Payload: Returns event.detail containing the payload of a Custom Event or Direct Call Rule
  - Direct Call Rule Identifier: Returns event.identifier containing the identifier of a Direct Call Rule
- JavaScript Tools: Wrappers for 15 common JavaScript operations for:
  - Basic string manipulation (capitalize, uppercase, lowercase, replace, substring, regex match, first- and last index)
  - Basic array operations (split, join, pop, shift)
  - Basic universal operations (slice, length)
- Visitor Attributes: Almost 1:1 copy of the Visitor Attributes condition, providing information about the user:
  - Browser Family
  - Browser Window Size
  - Device Type
  - Operating System
  - Screen Size

## Related Issue

#51 

## Motivation and Context

As described in #51, this pull requests adds Data Elements that aim to reduce the need for Custom Code Data Elements to 
- retrieve information about the runtime environment
- retrieve information about the visitor, which is already available in conditions
- return values on a condition in "If... Then... Else..."-style
- return values that have been transformed using basic JS operations like substrings

In my current and every previous company, we need to maintain our own private extension to have the described functionality. I know that we are not alone with this, so I feel like that basic functionality should be included in the Core extension so that it can be maintained centrally. There is not a lot of actual "logic" in those Data Elements, they just help us to keep our Launch properties maintainable for non-developers by avoiding tons of custom code in Data Elements (or even conditions). If any of the functionality would find its way into the Core extension, we would be super happy.

## Screenshots (if appropriate):
image
image
image
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project. (I think? I'm on Windows, so I can't run the linter)
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (Would be happy to help)
- [ ] All tests pass and I've made any necessary test changes. (Tests won't run on Windows, so couldn't go into this)
- [x] I have run the extension sandbox successfully.

### CODE REVIEW

**Comment by tyssejc** [comment]
Nice work @frederikwerner ! If this doesn't get pulled into the core extension, a lot of people would use it as a separate extension (myself included).

**Comment by zkorczyc** [comment]
I am So for it. It is a cool ad on that I have already ideas how to use.

**Comment by anilytics** [comment]
This is great stuff @frederikwerner  Hope this makes it.

**Comment by patrickhegnauer** [comment]
Nice work :), I do have most of them also in a private extension. A timestamp data element is also very useful, where you can config the format as preferred e.g. YYYY-MM-DD HH:MM:SS

**Comment by dompuiu** [comment]
@frederikwerner  We made some changes starting from your code and we now have this PR: https://github.com/adobe/reactor-extension-core/pull/61 . Thank you for your contribution! 

I will close the current PR.

**Pull request closed without merging**
