### PR TITLE
Add Constant Data Element Type

### PR DESCRIPTION
**Pull request by janexner**
Add a "Constant" Data Element Type

## Description

The "Constant" Data Element Type allows users to make Data Elements that have a constant value.

## Motivation and Context

When using Launch, there is often a need to keep things configurable, yet constant. A constant Data Element Type is highly useful for items like a report suite ID, or a tracking server.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All tests pass and I've made any necessary test changes.
- [ ] I have run the extension sandbox successfully.

### CODE REVIEW

**Comment by Aaronius** [comment]
We'll need to add the appropriate information to extension.json, add a test for the library module (I know there's not much logic), and get approval from @thebenrob from a product perspective. After it's merged, we can work internally to get it documented.

**Comment by janexner** [comment]
Done

**Comment by Aaronius** [comment]
Thanks @janexner! I'll do a final manual test next week before merging. Is there a use case for supporting numbers and booleans? I'm not suggesting you need to do the work; I'm just getting an idea of how this might be made even more useful.

**Comment by janexner** [comment]
There might be, yes. I haven't built it in because JS is tolerant enough in most cases when the constant is used.
In the UI, it would make it easier to validate user input, so maybe it should be done...

**Comment by Aaronius** [comment]
Thanks @janexner!

**Pull request merged**
